export as1czt
CDIR=../common
EXE=cztgaas

SOURCES= main.cpp cztgaas_v2.cpp $(CDIR)/utils.cpp $(CDIR)/cztstring.cpp $(CDIR)/coordinateTrasformation.cpp $(CDIR)/level1handler.cpp $(CDIR)/level2validation.cpp $(CDIR)/caldbHandler.cpp $(CDIR)/errorHandler.cpp $(CDIR)/Mvector.cpp $(CDIR)/mkfRegeneration.cpp $(CDIR)/badpixCALDB.cpp $(CDIR)/cztHeaderParam.cpp
include $(as1czt)/makefile.common
