export as1czt
CDIR=../common

EXE=cztrspgen

SOURCES= main.cpp cztrspgen.cpp cztshadowgen.cpp $(CDIR)/utils.cpp $(CDIR)/errorHandler.cpp $(CDIR)/cztstring.cpp  $(CDIR)/level2validation.cpp $(CDIR)/cztHeaderParam.cpp $(CDIR)/badpixCALDB.cpp $(CDIR)/caldbHandler.cpp $(CDIR)/maskGeometry.cpp $(CDIR)/Exposure.cpp $(CDIR)/detectorGeometry.cpp 

include $(as1czt)/makefile.common
