/* 
 * @file  errorHandler.h
 * @author Tanul Gupta
 * @date Created on Sep 16, 2015, 1:03 PM
 * @brief Handles error
 * @details This module contains classes and functions to handle error
 * @version 0.2.0
 */

#ifndef ERRORHANDLER_H
#define ERRORHANDLER_H

#include <vector>
#include <string>

typedef int LogSeverity;
const int errINFO=0;
const int errWARNING=1;
const int errERROR=2;
const int errFATAL=3;

typedef int ErrorCodes;
const int WARNING=1;
const int IMPROPER_INPUT=2;
const int NO_OUTPUT_POSSIBLE=3;
const int IMPROPER_GTI=4;
const int FILE_NOT_FOUND=5;
const int MULTIPLE_FILES_FOUND=6;
const int DIRECTORY_NOT_FOUND=7;
const int EMPTY_DIRECTORY=8;
const int ERROR_OPENING_DIRECTORY = 8;
const int RECORD_DOES_NOT_EXIST=100;
const int TABLE_STRUCTURE_NOT_COMPLETE=101;
const int VECTOR_2D_GENERATION_ERROR=102;
const int TABLE_READ_ERROR = 103;
const int INVALID_CALDB_FILETYPE=104;
const int INVALID_L1_BASEPATH=105;
const int EXTRAPOLATION_REQUIRED=106;
const int FITTING_NOT_POSSIBLE=121;
const int ERROR_CREATING_FITS_FROM_TEMPLATE=122;
const int ERROR_WRITING_FITS_COLUMN=123;
const int IMPROPER_INPUT_FITS_DATATYPE=124;
const int ERROR_READING_FITS_IMAGE=125;
const int UNABLE_TO_WRITE=126;
using namespace std;

class ErrorHandler{
public:
    LogSeverity severity;  // 0: INFO
                   // 1: WARNING
                   // 2: ERROR
                   // 3: FATAL
    string errorMsg;
    vector<string> warningMsg;
    char fitsErrMsg[1000];
    char fitsErrTxt[100];
    ErrorCodes errorStatus; //set only if error is not related to cfitsio
    int fitsErrorStatus;
    bool fitsflag; //whether the error is generated by fits
    
    
    ErrorHandler();
};

#endif /* ERRORHANDLER_H */