export as1czt
CDIR=../common

EXE=cztflagbadpix

SOURCES= main.cpp cztflagbadpix.cpp $(CDIR)/utils.cpp $(CDIR)/cztstring.cpp $(CDIR)/badpixCALDB.cpp $(CDIR)/errorHandler.cpp

include $(as1czt)/makefile.common
