export as1czt
CDIR=../common
EXE=cztgtigen
SOURCES= main.cpp cztgtigenv2.cpp $(CDIR)/utils.cpp $(CDIR)/validations.cpp $(CDIR)/level1handler.cpp $(CDIR)/caldbHandler.cpp $(CDIR)/level2validation.cpp $(CDIR)/errorHandler.cpp $(CDIR)/cztstring.cpp $(CDIR)/Mvector.cpp $(CDIR)/mkfRegeneration.cpp $(CDIR)/badpixCALDB.cpp $(CDIR)/cztHeaderParam.cpp $(CDIR)/gtiHandler.cpp 
include $(as1czt)/makefile.common
