export as1czt
CDIR=../common

EXE=cztbunchclean

SOURCES= main.cpp cztbunchcleanv2.cpp $(CDIR)/utils.cpp $(CDIR)/errorHandler.cpp $(CDIR)/cztstring.cpp $(CDIR)/caldbHandler.cpp $(CDIR)/level2validation.cpp $(CDIR)/cztHeaderParam.cpp  $(CDIR)/badpixCALDB.cpp  

include $(as1czt)/makefile.common
