export as1czt
CDIR=../common
EXE=cztdpigen

SOURCES= main.cpp cztdpigen_v2.cpp $(CDIR)/utils.cpp $(CDIR)/caldbHandler.cpp $(CDIR)/level2validation.cpp $(CDIR)/cztstring.cpp $(CDIR)/validations.cpp $(CDIR)/errorHandler.cpp $(CDIR)/badpixCALDB.cpp $(CDIR)/cztHeaderParam.cpp
include $(as1czt)/makefile.common
