export as1czt
CDIR=../common
EXE=cztdatasel

SOURCES= main.cpp cztdatasel.cpp $(CDIR)/utils.cpp $(CDIR)/errorHandler.cpp $(CDIR)/cztstring.cpp $(CDIR)/cztHeaderParam.cpp
include $(as1czt)/makefile.common
