export as1czt
CDIR=../common
EXE=cztimage

SOURCES= main.cpp cztimage_v2.cpp $(CDIR)/utils.cpp $(CDIR)/validations.cpp  \
		$(CDIR)/ExpMap.cpp $(CDIR)/jpeg_handling.cpp \
		$(CDIR)/linalg.cpp $(CDIR)/alglibinternal.cpp $(CDIR)/alglibmisc.cpp $(CDIR)/Exposure.cpp\
		$(CDIR)/ap.cpp $(CDIR)/cztstring.cpp $(CDIR)/caldbHandler.cpp $(CDIR)/coordinateTrasformation.cpp $(CDIR)/level1handler.cpp $(CDIR)/level2validation.cpp $(CDIR)/maskGeometry.cpp\
		$(CDIR)/errorHandler.cpp $(CDIR)/badpixCALDB.cpp $(CDIR)/detectorGeometry.cpp $(CDIR)/Mvector.cpp $(CDIR)/mkfRegeneration.cpp $(CDIR)/cztHeaderParam.cpp
include $(as1czt)/makefile.common
