export as1czt
CDIR=../common
EXPMAPDIR=../cztexpmap
EXE=cztscience2event

SOURCES= main.cpp $(CDIR)/caldbHandler.cpp $(CDIR)/level1handler.cpp $(CDIR)/utils.cpp $(CDIR)/cztstring.cpp $(CDIR)/level2validation.cpp $(CDIR)/l1evtdecode.cpp $(CDIR)/macrodef.h $(CDIR)/errorHandler.cpp cztscience2event.cpp $(CDIR)/badpixCALDB.cpp $(CDIR)/cztHeaderParam.cpp
include $(as1czt)/makefile.common
