export as1czt
CDIR=../common

EXE=cztpixclean

SOURCES= main.cpp cztpixclean.cpp $(CDIR)/utils.cpp $(CDIR)/errorHandler.cpp $(CDIR)/cztstring.cpp $(CDIR)/caldbHandler.cpp $(CDIR)/level2validation.cpp $(CDIR)/cztHeaderParam.cpp  $(CDIR)/badpixCALDB.cpp

include $(as1czt)/makefile.common
