export as1czt
CDIR=../common
EXE=cztpha2energy
SOURCES= main.cpp cztpha2energyv2.cpp $(CDIR)/utils.cpp $(CDIR)/cztstring.cpp $(CDIR)/caldbHandler.cpp $(CDIR)/level2validation.cpp $(CDIR)/errorHandler.cpp $(CDIR)/badpixCALDB.cpp $(CDIR)/cztHeaderParam.cpp
include $(as1czt)/makefile.common

