export as1czt
CDIR=../common

EXE=cztbindata

SOURCES3=radec2CZTI.f

SOURCES= main.cpp cztbindata.cpp cztshadowgen.cpp $(CDIR)/utils.cpp $(CDIR)/cztstring.cpp $(CDIR)/Exposure.cpp $(CDIR)/badpixCALDB.cpp  $(CDIR)/detectorGeometry.cpp $(CDIR)/errorHandler.cpp $(CDIR)/maskGeometry.cpp $(CDIR)/coordinateTrasformation.cpp $(CDIR)/level1handler.cpp $(CDIR)/level2validation.cpp $(CDIR)/validations.cpp $(CDIR)/caldbHandler.cpp $(CDIR)/Mvector.cpp $(CDIR)/mkfRegeneration.cpp $(CDIR)/cztHeaderParam.cpp

include $(as1czt)/makefile.common

